{"uuid": "d72f7102-1a4a-4e47-882a-839b3b56e1a5", "children": ["11f17a70-9e34-43dd-88fd-b94c1c998d3c"], "befores": [{"name": "get_driver", "status": "passed", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'C:\\Users\\vijay.kiran\\Desktop\\Lilly_app_automation\\SupportLibraries\\../MobileApp/lillydevicetestapprelease.apk' does not exist or is not accessible\n\n", "trace": "  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 180, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 868, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 736, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\vijay.kiran\\Desktop\\Lilly_app_automation\\TestScripts\\conftest.py\", line 9, in get_driver\n    driver = df.get_driver_instance()\n  File \"C:\\Users\\vijay.kiran\\Desktop\\Lilly_app_automation\\SupportLibraries\\driver_factory.py\", line 43, in get_driver_instance\n    desired_capabilities=desired_caps)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 94, in __init__\n    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 135, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1542816489097, "stop": 1542816489141}], "start": 1542816489097, "stop": 1542816489281}