{"uuid": "e786e117-361c-4638-8368-8b1ded957e5d", "children": ["d67fb8b2-b8f5-4584-8e77-776c9be33e1f"], "befores": [{"name": "get_driver", "status": "passed", "start": 1542819180109, "stop": 1542819207529}], "afters": [{"name": "get_driver::teardown", "status": "passed", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session/9986824b-2ea5-4bf5-9f8c-e734ce35c66f/appium/app/reset (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F17E4C2AC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 174, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 740, in teardown\n    next(it)\n  File \"C:\\Users\\vijay.kiran\\Desktop\\Lilly_app_automation\\TestScripts\\conftest.py\", line 17, in get_driver\n    driver.reset()\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 636, in reset\n    self.execute(Command.RESET)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 402, in _request\n    resp = http.request(method, url, body=body, headers=headers)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\request.py\", line 72, in request\n    **urlopen_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\request.py\", line 150, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 323, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 638, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 398, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1542819243549, "stop": 1542819247566}], "start": 1542819180109, "stop": 1542819247566}