{"uuid": "ac867204-148c-4432-b961-ef8ee091b202", "children": ["a59c36f8-7997-4d2b-b8e1-869629f25cde"], "befores": [{"name": "get_driver", "status": "passed", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168FAFEE588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 180, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 868, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 736, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\vijay.kiran\\Desktop\\Lilly_app_automation\\TestScripts\\conftest.py\", line 9, in get_driver\n    driver = df.get_driver_instance()\n  File \"C:\\Users\\vijay.kiran\\Desktop\\Lilly_app_automation\\SupportLibraries\\driver_factory.py\", line 43, in get_driver_instance\n    desired_capabilities=desired_caps)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 94, in __init__\n    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 135, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 402, in _request\n    resp = http.request(method, url, body=body, headers=headers)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\request.py\", line 72, in request\n    **urlopen_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\request.py\", line 150, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 323, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 667, in urlopen\n    **response_kw)\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 638, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"c:\\users\\vijay.kiran\\desktop\\lilly_app_automation\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 398, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1542834419363, "stop": 1542834424493}], "start": 1542834419363, "stop": 1542834425002}